// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn () -> DartFnFuture < Vec < Block > > + Send + Sync >>>
abstract class ArcFnDartFnFutureVecBlock implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (String) -> DartFnFuture < () > + Send + Sync >>>
abstract class ArcFnStringDartFnFuture implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (String , String) -> DartFnFuture < () > + Send + Sync >>>
abstract class ArcFnStringStringDartFnFuture implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn Fn (String , String , String) -> DartFnFuture < () > + Send + Sync >>>
abstract class ArcFnStringStringStringDartFnFuture
    implements RustOpaqueInterface {}
