// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `flush_pending_writes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `create_block`, `create_blocks`, `create_new`, `delete_block`, `delete_blocks`, `dispose`, `get_all_blocks`, `get_block`, `get_blocks`, `list_children`, `move_block`, `open_existing`, `update_block`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterPbtBackend>>
abstract class FlutterPbtBackend implements RustOpaqueInterface {}
