// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_data_to_block`, `execute_command`, `new_block_to_data`, `next_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `create_block`, `create_blocks`, `delete_block`, `delete_blocks`, `get_all_blocks`, `get_block`, `get_blocks`, `get_root_blocks`, `list_children`, `move_block`, `update_block`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterUiBackend>>
abstract class FlutterUiBackend implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new FlutterUiBackend
  ///
  /// Returns (backend, command_rx) where command_rx should be passed to Flutter
  static Future<(FlutterUiBackend, UnboundedReceiverUiRequest)> newInstance() =>
      RustLib.instance.api.crateApiFlutterUiBackendFlutterUiBackendNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< UnboundedReceiver < UiRequest >>>
abstract class UnboundedReceiverUiRequest implements RustOpaqueInterface {}
