// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'flutter_pbt_backend.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `apply`, `check_invariants`, `init_test`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterBlockTreeTest>>
abstract class FlutterBlockTreeTest implements RustOpaqueInterface {
  FlutterPbtBackend get backend;

  Map<String, String> get idMap;

  set backend(FlutterPbtBackend backend);

  set idMap(Map<String, String> idMap);
}
