// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/query_render/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Placeholder function to ensure FRB generates full types for query-render
/// This will be replaced with actual implementation in Phase 4.1
Future<RenderSpec> dummyRenderSpec() =>
    RustLib.instance.api.crateApiQueryRenderApiDummyRenderSpec();

/// Placeholder to ensure Arg type is generated
Future<Arg> dummyArg() => RustLib.instance.api.crateApiQueryRenderApiDummyArg();

/// Placeholder to ensure BinaryOperator type is generated
Future<BinaryOperator> dummyBinaryOp() =>
    RustLib.instance.api.crateApiQueryRenderApiDummyBinaryOp();
