// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

@freezed
sealed class ApiError with _$ApiError implements FrbException {
  const ApiError._();

  const factory ApiError.blockNotFound({required String id}) =
      ApiError_BlockNotFound;
  const factory ApiError.documentNotFound({required String docId}) =
      ApiError_DocumentNotFound;
  const factory ApiError.cyclicMove({
    required String id,
    required String targetParent,
  }) = ApiError_CyclicMove;
  const factory ApiError.invalidOperation({required String message}) =
      ApiError_InvalidOperation;
  const factory ApiError.networkError({required String message}) =
      ApiError_NetworkError;
  const factory ApiError.internalError({required String message}) =
      ApiError_InternalError;
}

@freezed
sealed class BlockChange with _$BlockChange {
  const BlockChange._();

  /// Block was created
  const factory BlockChange.created({
    required String id,
    required String parentId,
    required String content,
    required List<String> children,
    required ChangeOrigin origin,
  }) = BlockChange_Created;

  /// Block content was updated
  const factory BlockChange.updated({
    required String id,
    required String content,
    required ChangeOrigin origin,
  }) = BlockChange_Updated;

  /// Block was deleted
  const factory BlockChange.deleted({
    required String id,
    required ChangeOrigin origin,
  }) = BlockChange_Deleted;

  /// Block was moved
  const factory BlockChange.moved({
    required String id,
    required String newParent,
    String? after,
    required ChangeOrigin origin,
  }) = BlockChange_Moved;
}

/// Origin of a change event (local vs. remote).
enum ChangeOrigin {
  /// Change initiated by this client
  local,

  /// Change received from P2P sync
  remote,
}

@freezed
sealed class StreamPosition with _$StreamPosition {
  const StreamPosition._();

  /// Start from the beginning
  const factory StreamPosition.beginning() = StreamPosition_Beginning;

  /// Start from a specific version
  const factory StreamPosition.version(Uint8List field0) =
      StreamPosition_Version;
}
